import type { Metadata } from "next";
import { Quantico } from "next/font/google";
import "@/app/globals.css";

const quantico = Quantico({
  weight: "400",
  style: 'normal'
});

export const metadata: Metadata = {
  title: "Daily Insight",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${quantico.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
